/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    run
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Test_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
