/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Multiply */

#ifndef _Included_Multiply
#define _Included_Multiply
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Multiply
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Multiply_multiply
  (JNIEnv *, jclass, jint base, jint rate);

#ifdef __cplusplus
}
#endif
#endif
