/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SimpleIO */

#ifndef _Included_SimpleIO
#define _Included_SimpleIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SimpleIO
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SimpleIO_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
